/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms.ijse.layered.view;

/**
 *
 * @author Dileep Edirisinghe
 */
public class CustomerView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public CustomerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        year_TextField = new javax.swing.JTextField();
        custID_txtF = new javax.swing.JTextField();
        day_ComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        firstName_txtF = new javax.swing.JTextField();
        month_ComboBox = new javax.swing.JComboBox<>();
        maleFemail_jComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lastName_txtF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nic_txtF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addressL1_txtF = new javax.swing.JTextField();
        addressL2_txtF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        postaCode_txtF = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        city_txtF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        LandPhone_txtF = new javax.swing.JTextField();
        mobile_txtF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        email_txtF = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stDetailsTable_Table = new javax.swing.JTable();
        homeBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        searchCustName_txtF = new javax.swing.JTextField();
        searchCustID_txtF = new javax.swing.JTextField();
        clearBtn1 = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Customer Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 0, 290, 32);

        jPanel10.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Details"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setToolTipText("");
        jPanel2.setName(""); // NOI18N
        jPanel2.setLayout(null);

        jLabel17.setText("Land Phone Number:");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 110, 120, 16);

        jLabel18.setText("WhatsApp Number:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 80, 120, 16);

        jLabel19.setText("Emergency Number:");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 50, 120, 16);

        jLabel20.setText("Mobile Number:");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 20, 120, 16);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 320, 470, 150);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Customer ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 110, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("First Name:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 80, 16);

        year_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                year_TextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(year_TextField);
        year_TextField.setBounds(440, 120, 60, 22);

        custID_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custID_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(custID_txtF);
        custID_txtF.setBounds(120, 30, 180, 22);

        day_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(day_ComboBox);
        day_ComboBox.setBounds(150, 120, 50, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Last Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 90, 120, 16);

        jLabel6.setText("Year");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 120, 50, 16);

        firstName_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstName_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(firstName_txtF);
        firstName_txtF.setBounds(120, 60, 380, 22);

        month_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel1.add(month_ComboBox);
        month_ComboBox.setBounds(280, 120, 100, 22);

        maleFemail_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(maleFemail_jComboBox);
        maleFemail_jComboBox.setBounds(120, 150, 90, 22);

        jLabel9.setText("Day");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 120, 50, 16);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Birth Date:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 120, 80, 16);

        jLabel11.setText("Month");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(230, 120, 50, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 150, 80, 16);

        lastName_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastName_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(lastName_txtF);
        lastName_txtF.setBounds(120, 90, 380, 22);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("NIC Number:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 180, 80, 16);

        nic_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nic_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(nic_txtF);
        nic_txtF.setBounds(120, 180, 380, 22);

        jPanel10.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 220);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Address"));
        jPanel5.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Address Line 1:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 30, 120, 16);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Address Line 2:");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 60, 120, 16);

        addressL1_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressL1_txtFActionPerformed(evt);
            }
        });
        jPanel5.add(addressL1_txtF);
        addressL1_txtF.setBounds(120, 30, 380, 22);

        addressL2_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressL2_txtFActionPerformed(evt);
            }
        });
        jPanel5.add(addressL2_txtF);
        addressL2_txtF.setBounds(120, 60, 380, 22);

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Postal Code:");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(320, 90, 120, 16);

        postaCode_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postaCode_txtFActionPerformed(evt);
            }
        });
        jPanel5.add(postaCode_txtF);
        postaCode_txtF.setBounds(410, 90, 90, 22);

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("City:");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(10, 90, 120, 16);

        city_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                city_txtFActionPerformed(evt);
            }
        });
        jPanel5.add(city_txtF);
        city_txtF.setBounds(120, 90, 140, 22);

        jPanel10.add(jPanel5);
        jPanel5.setBounds(10, 380, 510, 170);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Phone Number/ Email"));
        jPanel3.setToolTipText("");
        jPanel3.setName(""); // NOI18N
        jPanel3.setLayout(null);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Land Phone No.:");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(10, 60, 120, 16);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setToolTipText("");
        jPanel4.setName(""); // NOI18N
        jPanel4.setLayout(null);

        jLabel25.setText("Land Phone Number:");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(10, 110, 120, 16);

        jLabel26.setText("WhatsApp Number:");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(10, 80, 120, 16);

        jLabel27.setText("Emergency Number:");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(10, 50, 120, 16);

        jLabel28.setText("Mobile Number:");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(10, 20, 120, 16);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(40, 320, 470, 150);

        LandPhone_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LandPhone_txtFActionPerformed(evt);
            }
        });
        jPanel3.add(LandPhone_txtF);
        LandPhone_txtF.setBounds(120, 60, 230, 22);

        mobile_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_txtFActionPerformed(evt);
            }
        });
        jPanel3.add(mobile_txtF);
        mobile_txtF.setBounds(120, 30, 230, 22);

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Mobile No.:");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(10, 30, 120, 16);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("E-Mail:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(10, 90, 120, 16);

        email_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtFActionPerformed(evt);
            }
        });
        jPanel3.add(email_txtF);
        email_txtF.setBounds(120, 90, 230, 22);

        jPanel10.add(jPanel3);
        jPanel3.setBounds(10, 240, 510, 130);

        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel10.add(updateBtn);
        updateBtn.setBounds(150, 580, 130, 30);

        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        jPanel10.add(clearBtn);
        clearBtn.setBounds(390, 580, 130, 30);

        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel10.add(saveBtn);
        saveBtn.setBounds(10, 580, 130, 30);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(0, 40, 530, 620);

        jPanel8.setLayout(null);

        jPanel7.setLayout(null);

        stDetailsTable_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(stDetailsTable_Table);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(0, 10, 820, 440);

        homeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel7.add(homeBtn);
        homeBtn.setBounds(650, 480, 80, 30);

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel7.add(logoutBtn);
        logoutBtn.setBounds(740, 480, 80, 30);

        deleteBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel7.add(deleteBtn);
        deleteBtn.setBounds(0, 480, 130, 30);

        jPanel8.add(jPanel7);
        jPanel7.setBounds(10, 100, 820, 520);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Customer's Name:");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(20, 40, 120, 16);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Customer ID:");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(20, 10, 100, 16);
        jPanel9.add(searchCustName_txtF);
        searchCustName_txtF.setBounds(150, 40, 330, 22);
        jPanel9.add(searchCustID_txtF);
        searchCustID_txtF.setBounds(150, 10, 90, 22);

        clearBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn1.setText("Clear");
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });
        jPanel9.add(clearBtn1);
        clearBtn1.setBounds(740, 10, 72, 50);

        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel9.add(searchBtn);
        searchBtn.setBounds(610, 10, 110, 50);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(10, 20, 820, 70);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(530, 40, 840, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void year_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_year_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_year_TextFieldActionPerformed

    private void custID_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custID_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custID_txtFActionPerformed

    private void firstName_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstName_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstName_txtFActionPerformed

    private void lastName_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastName_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastName_txtFActionPerformed

    private void nic_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nic_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nic_txtFActionPerformed

    private void addressL1_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressL1_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressL1_txtFActionPerformed

    private void addressL2_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressL2_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressL2_txtFActionPerformed

    private void postaCode_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postaCode_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postaCode_txtFActionPerformed

    private void city_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_city_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_city_txtFActionPerformed

    private void LandPhone_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LandPhone_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LandPhone_txtFActionPerformed

    private void mobile_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobile_txtFActionPerformed

    private void email_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtFActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String index = custID_txtF.getText();
        String name = firstName_txtF.getText();
        String initials = lastName_txtF.getText();

        String day = (String) day_ComboBox.getSelectedItem();
        String month = (String) month_ComboBox.getSelectedItem();
        int year = Integer.parseInt(year_TextField.getText());

        String birthDay = day + "-" + month + "-" + year;
        String permenantAddress = addressL1_txtF.getText();
        String temporaryAddress = addressL2_txtF.getText();
        int homeNo = Integer.parseInt(LandPhone_txtF.getText());
        int mobileNo = Integer.parseInt(mobile_txtF.getText());

        //db.DbControl.executeUpdate("INSERT INTO student (`index`,`full_name`,`Intitals`,`special_need`,`birthday`,`permenant_address`,`tempory_address`,`emergency_no`,`whatsapp_no`,`home_no`,`mobile_no`)" + "VALUES ('" + index + "','" + name + "','" + initials + "','" + specialNeeds + "','" + birthDay + "','" + permenantAddress + "', '" + temporaryAddress + "', " + emergencyNo + ", " + whatsAppNumber + ", " + homeNo + "," + mobileNo + ")");
    }//GEN-LAST:event_updateBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        //new Home().setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LandPhone_txtF;
    private javax.swing.JTextField addressL1_txtF;
    private javax.swing.JTextField addressL2_txtF;
    private javax.swing.JTextField city_txtF;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JTextField custID_txtF;
    private javax.swing.JComboBox<String> day_ComboBox;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField email_txtF;
    private javax.swing.JTextField firstName_txtF;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastName_txtF;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JComboBox<String> maleFemail_jComboBox;
    private javax.swing.JTextField mobile_txtF;
    private javax.swing.JComboBox<String> month_ComboBox;
    private javax.swing.JTextField nic_txtF;
    private javax.swing.JTextField postaCode_txtF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchCustID_txtF;
    private javax.swing.JTextField searchCustName_txtF;
    private javax.swing.JTable stDetailsTable_Table;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField year_TextField;
    // End of variables declaration//GEN-END:variables
}
