/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms.ijse.layered.view;
import java.awt.Color;
/**
 *
 * @author Dileep Edirisinghe
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jSlider2 = new javax.swing.JSlider();
        jSlider3 = new javax.swing.JSlider();
        jSlider4 = new javax.swing.JSlider();
        jSlider6 = new javax.swing.JSlider();
        jSlider7 = new javax.swing.JSlider();
        jSlider8 = new javax.swing.JSlider();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jSlider5 = new javax.swing.JSlider();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HotelLogo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 190, 60);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Details");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(60, 20, 170, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 410, 310, 70);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dashboard");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(60, 20, 120, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 130, 310, 70);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logout");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(60, 20, 110, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 550, 310, 70);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Edit Reservation Details");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(60, 20, 230, 30);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 270, 310, 70);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Edit Rooms");
        jPanel6.add(jLabel6);
        jLabel6.setBounds(60, 20, 110, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 480, 310, 70);

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });
        jPanel7.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Reservation Process");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(60, 20, 200, 30);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 200, 310, 70);

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel13MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel13MouseExited(evt);
            }
        });
        jPanel13.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Employees");
        jPanel13.add(jLabel20);
        jLabel20.setBounds(60, 20, 110, 30);

        jPanel1.add(jPanel13);
        jPanel13.setBounds(0, 340, 310, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 310, 710);

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));
        jPanel8.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Dashboard");
        jPanel8.add(jLabel8);
        jLabel8.setBounds(30, 60, 180, 40);

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(0, 102, 102));
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.add(jTextField1);
        jTextField1.setBounds(120, 10, 64, 50);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Rooms occupied");
        jPanel10.add(jLabel13);
        jLabel13.setBounds(20, 90, 160, 30);

        jPanel8.add(jPanel10);
        jPanel10.setBounds(470, 130, 200, 130);

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setLayout(null);

        jTextField2.setBackground(new java.awt.Color(0, 102, 102));
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel11.add(jTextField2);
        jTextField2.setBounds(120, 70, 64, 50);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Check-ins");
        jPanel11.add(jLabel9);
        jLabel9.setBounds(20, 10, 90, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("This Week");
        jPanel11.add(jLabel10);
        jLabel10.setBounds(20, 40, 90, 30);

        jPanel8.add(jPanel11);
        jPanel11.setBounds(30, 130, 200, 130);

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setLayout(null);

        jTextField3.setBackground(new java.awt.Color(0, 102, 102));
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel12.add(jTextField3);
        jTextField3.setBounds(120, 70, 64, 50);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Check-outs");
        jPanel12.add(jLabel11);
        jLabel11.setBounds(20, 10, 110, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("This Week");
        jPanel12.add(jLabel12);
        jLabel12.setBounds(20, 40, 90, 30);

        jPanel8.add(jPanel12);
        jPanel12.setBounds(250, 130, 200, 130);

        jLabel14.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Reservations");
        jPanel8.add(jLabel14);
        jLabel14.setBounds(30, 290, 130, 20);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Customer", "Room", "Date"
            }
        ));
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(8);
        }

        jTabbedPane4.addTab("Check-outs", jScrollPane3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Customer", "Room", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(8);
        }

        jTabbedPane4.addTab("Check-ins", jScrollPane1);

        jPanel8.add(jTabbedPane4);
        jTabbedPane4.setBounds(30, 330, 640, 350);

        jPanel9.setBackground(new java.awt.Color(0, 43, 87));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jTextField4.setBackground(new java.awt.Color(0, 43, 87));
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField4);
        jTextField4.setBounds(210, 90, 80, 30);

        jTextField5.setBackground(new java.awt.Color(1, 8, 37));
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField5);
        jTextField5.setBounds(30, 60, 70, 63);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Revenue");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(220, 130, 70, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Reserved");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(30, 130, 70, 20);

        jTextField6.setBackground(new java.awt.Color(1, 8, 37));
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextField6);
        jTextField6.setBounds(120, 60, 70, 63);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Customers");
        jPanel9.add(jLabel17);
        jLabel17.setBounds(120, 130, 70, 20);

        jSlider1.setMajorTickSpacing(100);
        jSlider1.setMaximum(1500);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setValue(0);
        jPanel9.add(jSlider1);
        jSlider1.setBounds(300, 250, 30, 250);

        jSlider2.setForeground(new java.awt.Color(255, 255, 255));
        jSlider2.setMajorTickSpacing(100);
        jSlider2.setMaximum(1500);
        jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider2.setPaintLabels(true);
        jSlider2.setToolTipText("");
        jSlider2.setValue(0);
        jSlider2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSlider2.setEnabled(false);
        jPanel9.add(jSlider2);
        jSlider2.setBounds(-20, 250, 90, 250);

        jSlider3.setMajorTickSpacing(100);
        jSlider3.setMaximum(1500);
        jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider3.setValue(0);
        jPanel9.add(jSlider3);
        jSlider3.setBounds(100, 250, 30, 250);

        jSlider4.setMajorTickSpacing(100);
        jSlider4.setMaximum(1500);
        jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider4.setValue(0);
        jPanel9.add(jSlider4);
        jSlider4.setBounds(140, 250, 30, 250);

        jSlider6.setMajorTickSpacing(100);
        jSlider6.setMaximum(1500);
        jSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider6.setValue(0);
        jPanel9.add(jSlider6);
        jSlider6.setBounds(180, 250, 30, 250);

        jSlider7.setMajorTickSpacing(100);
        jSlider7.setMaximum(1500);
        jSlider7.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider7.setValue(0);
        jPanel9.add(jSlider7);
        jSlider7.setBounds(220, 250, 30, 250);

        jSlider8.setMajorTickSpacing(100);
        jSlider8.setMaximum(1500);
        jSlider8.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider8.setValue(0);
        jPanel9.add(jSlider8);
        jSlider8.setBounds(260, 250, 30, 250);

        jTextField7.setBackground(new java.awt.Color(0, 43, 87));
        jTextField7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(jTextField7);
        jTextField7.setBounds(300, 500, 30, 20);

        jTextField8.setBackground(new java.awt.Color(0, 43, 87));
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(jTextField8);
        jTextField8.setBounds(60, 500, 30, 20);

        jTextField9.setBackground(new java.awt.Color(0, 43, 87));
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(jTextField9);
        jTextField9.setBounds(100, 500, 30, 20);

        jTextField10.setBackground(new java.awt.Color(0, 43, 87));
        jTextField10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(jTextField10);
        jTextField10.setBounds(140, 500, 30, 20);

        jTextField11.setBackground(new java.awt.Color(0, 43, 87));
        jTextField11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(jTextField11);
        jTextField11.setBounds(180, 500, 30, 20);

        jTextField12.setBackground(new java.awt.Color(0, 43, 87));
        jTextField12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(jTextField12);
        jTextField12.setBounds(220, 500, 30, 20);

        jTextField13.setBackground(new java.awt.Color(0, 43, 87));
        jTextField13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.add(jTextField13);
        jTextField13.setBounds(260, 500, 30, 20);

        jSlider5.setMajorTickSpacing(100);
        jSlider5.setMaximum(1500);
        jSlider5.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider5.setValue(0);
        jPanel9.add(jSlider5);
        jSlider5.setBounds(60, 250, 30, 250);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Weekly Stats");
        jPanel9.add(jLabel18);
        jLabel18.setBounds(30, 190, 150, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Today's Activities");
        jPanel9.add(jLabel19);
        jLabel19.setBounds(30, 10, 150, 30);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(690, 130, 350, 550);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(310, 0, 1060, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        jPanel2.setBackground(new Color(0, 51, 51)); // Change color to whatever you prefer
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        jPanel2.setBackground(null); // Revert to default color
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(new Color(0, 51, 51)); // Change color to whatever you prefer
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(null); // Revert to default color
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        jPanel5.setBackground(new Color(0, 51, 51)); // Change color to whatever you prefer
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(null); // Revert to default color
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(0, 51, 51)); // Change color to whatever you prefer
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(null); // Revert to default color
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        jPanel7.setBackground(new Color(0, 51, 51)); // Change color to whatever you prefer
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        jPanel7.setBackground(null); // Revert to default color
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(null); // Revert to default color
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setBackground(new Color(0, 51, 51)); // Change color to whatever you prefer
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jPanel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseEntered

    private void jPanel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel13MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider3;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JSlider jSlider5;
    private javax.swing.JSlider jSlider6;
    private javax.swing.JSlider jSlider7;
    private javax.swing.JSlider jSlider8;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
