/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms.ijse.layered.view;

/**
 *
 * @author Dileep Edirisinghe
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email_txtF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pw_PasswordField = new javax.swing.JPasswordField();
        keepMeSignedIn_CheckBox = new javax.swing.JCheckBox();
        forgotPW_Label = new javax.swing.JLabel();
        LoginBtn = new javax.swing.JButton();
        signup_Label = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hms/ijse/layered/images/Hotel-Bookings.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-30, 60, 570, 500);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 255, 255), new java.awt.Color(204, 204, 255)));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("HotelLogo");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(100, 20, 210, 60);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Log in");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 120, 140, 40);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Official Email Address");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 180, 190, 30);

        email_txtF.setBackground(new java.awt.Color(255, 255, 255));
        email_txtF.setForeground(new java.awt.Color(0, 0, 0));
        email_txtF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        email_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtFActionPerformed(evt);
            }
        });
        jPanel3.add(email_txtF);
        email_txtF.setBounds(30, 210, 300, 40);

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 260, 110, 30);

        pw_PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        pw_PasswordField.setForeground(new java.awt.Color(0, 0, 0));
        pw_PasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(pw_PasswordField);
        pw_PasswordField.setBounds(30, 290, 300, 40);

        keepMeSignedIn_CheckBox.setBackground(new java.awt.Color(255, 255, 255));
        keepMeSignedIn_CheckBox.setForeground(new java.awt.Color(0, 0, 0));
        keepMeSignedIn_CheckBox.setText("Keep  me signed in");
        keepMeSignedIn_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keepMeSignedIn_CheckBoxActionPerformed(evt);
            }
        });
        jPanel3.add(keepMeSignedIn_CheckBox);
        keepMeSignedIn_CheckBox.setBounds(30, 340, 140, 20);

        forgotPW_Label.setForeground(new java.awt.Color(0, 0, 153));
        forgotPW_Label.setText("Forgot Password?");
        jPanel3.add(forgotPW_Label);
        forgotPW_Label.setBounds(230, 340, 110, 16);

        LoginBtn.setBackground(new java.awt.Color(0, 102, 102));
        LoginBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LoginBtn.setForeground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Log in");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        jPanel3.add(LoginBtn);
        LoginBtn.setBounds(30, 390, 300, 30);

        signup_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signup_Label.setForeground(new java.awt.Color(0, 0, 153));
        signup_Label.setText("Sign up");
        jPanel3.add(signup_Label);
        signup_Label.setBounds(230, 460, 90, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Don't have an account?");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(90, 460, 150, 20);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(550, 20, 360, 550);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(230, 50, 930, 590);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1450, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtFActionPerformed

    private void keepMeSignedIn_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keepMeSignedIn_CheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keepMeSignedIn_CheckBoxActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField email_txtF;
    private javax.swing.JLabel forgotPW_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JCheckBox keepMeSignedIn_CheckBox;
    private javax.swing.JPasswordField pw_PasswordField;
    private javax.swing.JLabel signup_Label;
    // End of variables declaration//GEN-END:variables
}
