/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms.ijse.layered.view;

/**
 *
 * @author Dileep Edirisinghe
 */
public class ReservationView extends javax.swing.JFrame {

    /**
     * Creates new form CustomerView
     */
    public ReservationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        roomNo_txtF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        roomType_txtF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        checkOutTime_txtF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        checkOutDate_txtF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        resID_txtF = new javax.swing.JTextField();
        resDate_txtF = new javax.swing.JTextField();
        resTime_txtF = new javax.swing.JTextField();
        checkInDate_txtF = new javax.swing.JTextField();
        checkInTime_txtF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        custID_txtF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        custName_txtF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        noOfAdults_txtF = new javax.swing.JTextField();
        noOfChildren_txtF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        totalAmount_txtF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        specialReq_TextArea = new javax.swing.JTextArea();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        clearBtn2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stDetailsTable_Table = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        searchStName_txtF = new javax.swing.JTextField();
        searchStWithIndex_txtF = new javax.swing.JTextField();
        clearBtn1 = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        cancelResBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Reservation Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(580, 0, 260, 32);

        jPanel10.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reservation"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Reservation ID:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 30, 110, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Room No.:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 80, 16);

        roomNo_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNo_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(roomNo_txtF);
        roomNo_txtF.setBounds(120, 60, 100, 22);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Room Type:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 150, 120, 16);

        roomType_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomType_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(roomType_txtF);
        roomType_txtF.setBounds(120, 150, 380, 22);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Reservation Time:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 210, 110, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Est. Check-out Time:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 270, 120, 16);

        checkOutTime_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutTime_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(checkOutTime_txtF);
        checkOutTime_txtF.setBounds(400, 270, 100, 22);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Check-out Date:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 270, 110, 16);

        checkOutDate_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutDate_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(checkOutDate_txtF);
        checkOutDate_txtF.setBounds(120, 270, 100, 22);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Reservation Date:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 180, 120, 16);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Check-in Date:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 240, 110, 16);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Est. Check-in Time:");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(270, 240, 110, 16);

        resID_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resID_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(resID_txtF);
        resID_txtF.setBounds(120, 30, 100, 22);

        resDate_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resDate_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(resDate_txtF);
        resDate_txtF.setBounds(120, 180, 100, 22);

        resTime_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resTime_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(resTime_txtF);
        resTime_txtF.setBounds(120, 210, 100, 22);

        checkInDate_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInDate_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(checkInDate_txtF);
        checkInDate_txtF.setBounds(120, 240, 100, 22);

        checkInTime_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInTime_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(checkInTime_txtF);
        checkInTime_txtF.setBounds(400, 240, 100, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Customer ID:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 80, 16);

        custID_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custID_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(custID_txtF);
        custID_txtF.setBounds(120, 90, 100, 22);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Customer Name:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 120, 110, 16);

        custName_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custName_txtFActionPerformed(evt);
            }
        });
        jPanel1.add(custName_txtF);
        custName_txtF.setBounds(120, 120, 380, 22);

        jPanel10.add(jPanel1);
        jPanel1.setBounds(10, 10, 510, 320);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Other Details"));
        jPanel5.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("No. of Adults:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 30, 120, 16);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("No. of Children:");
        jPanel5.add(jLabel13);
        jLabel13.setBounds(10, 60, 110, 16);

        noOfAdults_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfAdults_txtFActionPerformed(evt);
            }
        });
        jPanel5.add(noOfAdults_txtF);
        noOfAdults_txtF.setBounds(120, 30, 100, 22);

        noOfChildren_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noOfChildren_txtFActionPerformed(evt);
            }
        });
        jPanel5.add(noOfChildren_txtF);
        noOfChildren_txtF.setBounds(120, 60, 100, 22);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Special Requests:");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(10, 90, 110, 16);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Total Amount:");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(10, 190, 110, 16);

        totalAmount_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmount_txtFActionPerformed(evt);
            }
        });
        jPanel5.add(totalAmount_txtF);
        totalAmount_txtF.setBounds(120, 190, 110, 22);

        specialReq_TextArea.setColumns(20);
        specialReq_TextArea.setRows(5);
        jScrollPane1.setViewportView(specialReq_TextArea);

        jPanel5.add(jScrollPane1);
        jScrollPane1.setBounds(120, 90, 380, 90);

        jPanel10.add(jPanel5);
        jPanel5.setBounds(10, 340, 510, 230);

        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel10.add(saveBtn);
        saveBtn.setBounds(10, 600, 130, 30);

        updateBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel10.add(updateBtn);
        updateBtn.setBounds(150, 600, 130, 30);

        clearBtn2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn2.setText("Clear");
        clearBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn2ActionPerformed(evt);
            }
        });
        jPanel10.add(clearBtn2);
        clearBtn2.setBounds(390, 600, 130, 30);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(0, 30, 520, 690);

        jPanel8.setLayout(null);

        jPanel7.setLayout(null);

        stDetailsTable_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(stDetailsTable_Table);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(0, 10, 820, 460);

        jPanel8.add(jPanel7);
        jPanel7.setBounds(10, 100, 820, 470);

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Reservation ID:");
        jPanel9.add(jLabel7);
        jLabel7.setBounds(20, 40, 120, 16);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Customer ID:");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(20, 10, 100, 16);
        jPanel9.add(searchStName_txtF);
        searchStName_txtF.setBounds(130, 40, 100, 22);
        jPanel9.add(searchStWithIndex_txtF);
        searchStWithIndex_txtF.setBounds(130, 10, 100, 22);

        clearBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn1.setText("Clear");
        clearBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtn1ActionPerformed(evt);
            }
        });
        jPanel9.add(clearBtn1);
        clearBtn1.setBounds(740, 10, 72, 50);

        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        jPanel9.add(searchBtn);
        searchBtn.setBounds(610, 10, 110, 50);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(10, 20, 820, 70);

        cancelResBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelResBtn.setText("Cancel Reservation");
        cancelResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelResBtnActionPerformed(evt);
            }
        });
        jPanel8.add(cancelResBtn);
        cancelResBtn.setBounds(10, 600, 180, 30);

        homeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        jPanel8.add(homeBtn);
        homeBtn.setBounds(660, 600, 80, 30);

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel8.add(logoutBtn);
        logoutBtn.setBounds(750, 600, 80, 30);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(520, 30, 850, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roomNo_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNo_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNo_txtFActionPerformed

    private void roomType_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomType_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomType_txtFActionPerformed

    private void checkOutTime_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutTime_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutTime_txtFActionPerformed

    private void checkOutDate_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutDate_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutDate_txtFActionPerformed

    private void resID_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resID_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resID_txtFActionPerformed

    private void resDate_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resDate_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resDate_txtFActionPerformed

    private void resTime_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resTime_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resTime_txtFActionPerformed

    private void checkInDate_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInDate_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInDate_txtFActionPerformed

    private void checkInTime_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInTime_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInTime_txtFActionPerformed

    private void custID_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custID_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custID_txtFActionPerformed

    private void custName_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custName_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custName_txtFActionPerformed

    private void noOfAdults_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfAdults_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfAdults_txtFActionPerformed

    private void noOfChildren_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noOfChildren_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noOfChildren_txtFActionPerformed

    private void totalAmount_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmount_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmount_txtFActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateBtnActionPerformed

    private void clearBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtn2ActionPerformed

    private void clearBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearBtn1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBtnActionPerformed

    private void cancelResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelResBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelResBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        //new Home().setVisible(true);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelResBtn;
    private javax.swing.JTextField checkInDate_txtF;
    private javax.swing.JTextField checkInTime_txtF;
    private javax.swing.JTextField checkOutDate_txtF;
    private javax.swing.JTextField checkOutTime_txtF;
    private javax.swing.JButton clearBtn1;
    private javax.swing.JButton clearBtn2;
    private javax.swing.JTextField custID_txtF;
    private javax.swing.JTextField custName_txtF;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField noOfAdults_txtF;
    private javax.swing.JTextField noOfChildren_txtF;
    private javax.swing.JTextField resDate_txtF;
    private javax.swing.JTextField resID_txtF;
    private javax.swing.JTextField resTime_txtF;
    private javax.swing.JTextField roomNo_txtF;
    private javax.swing.JTextField roomType_txtF;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchStName_txtF;
    private javax.swing.JTextField searchStWithIndex_txtF;
    private javax.swing.JTextArea specialReq_TextArea;
    private javax.swing.JTable stDetailsTable_Table;
    private javax.swing.JTextField totalAmount_txtF;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
