/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hms.ijse.layered.view;

/**
 *
 * @author Dileep Edirisinghe
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        regEmployee_Label = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email_txtF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pw_PasswordField = new javax.swing.JPasswordField();
        signupBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        empID_txtF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        confirmPW_PasswordField = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        login_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setMinimumSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HotelLogo");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 140, 210, 60);

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("for get employee ID.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 340, 650, 30);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Welcome to HotelName");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(30, 250, 240, 30);

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("We are so excited to have you here.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 280, 250, 30);

        regEmployee_Label.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        regEmployee_Label.setForeground(new java.awt.Color(0, 0, 51));
        regEmployee_Label.setText("here");
        jPanel1.add(regEmployee_Label);
        regEmployee_Label.setBounds(320, 310, 70, 30);

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("If you haven't registered as a employee, click ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 310, 290, 30);

        jPanel3.add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 560);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Sign up");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(620, 20, 110, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Official Email Address");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(520, 170, 160, 30);

        email_txtF.setBackground(new java.awt.Color(255, 255, 255));
        email_txtF.setForeground(new java.awt.Color(0, 0, 0));
        email_txtF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        email_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_txtFActionPerformed(evt);
            }
        });
        jPanel3.add(email_txtF);
        email_txtF.setBounds(520, 200, 300, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Password");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(520, 250, 110, 30);

        pw_PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        pw_PasswordField.setForeground(new java.awt.Color(0, 0, 0));
        pw_PasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(pw_PasswordField);
        pw_PasswordField.setBounds(520, 280, 300, 40);

        signupBtn.setBackground(new java.awt.Color(0, 102, 102));
        signupBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Sign up");
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });
        jPanel3.add(signupBtn);
        signupBtn.setBounds(520, 420, 90, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Employee ID");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(520, 90, 160, 30);

        empID_txtF.setBackground(new java.awt.Color(255, 255, 255));
        empID_txtF.setForeground(new java.awt.Color(0, 0, 0));
        empID_txtF.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        empID_txtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empID_txtFActionPerformed(evt);
            }
        });
        jPanel3.add(empID_txtF);
        empID_txtF.setBounds(520, 120, 300, 40);

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Confirm Password");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(520, 330, 160, 30);

        confirmPW_PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        confirmPW_PasswordField.setForeground(new java.awt.Color(0, 0, 0));
        confirmPW_PasswordField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(confirmPW_PasswordField);
        confirmPW_PasswordField.setBounds(520, 360, 300, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Already have an account?");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(520, 480, 150, 20);

        login_Label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_Label.setForeground(new java.awt.Color(0, 0, 153));
        login_Label.setText("Log in");
        jPanel3.add(login_Label);
        login_Label.setBounds(670, 480, 90, 20);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(230, 50, 930, 560);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1380, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtFActionPerformed

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupBtnActionPerformed

    private void empID_txtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empID_txtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empID_txtFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPW_PasswordField;
    private javax.swing.JTextField email_txtF;
    private javax.swing.JTextField empID_txtF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel login_Label;
    private javax.swing.JPasswordField pw_PasswordField;
    private javax.swing.JLabel regEmployee_Label;
    private javax.swing.JButton signupBtn;
    // End of variables declaration//GEN-END:variables
}
